export const templates: Record<string, string> = {
  "US": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}, {state} {postalCode}\n{country}\nTax ID: {taxNumber}`,
  "CA": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}, {state} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "MX": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}, {state}\n{country}\nTax Number: {taxNumber}`,
  "DE": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nUSt-IdNr.: {taxNumber}`,
  "FR": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{postalCode} {city}\n{country}\nNuméro TVA: {taxNumber}`,
  "IT": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nPartita IVA: {taxNumber}`,
  "ES": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nNIF: {taxNumber}`,
  "GB": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{postalCode}\n{country}\nVAT Reg No.: {taxNumber}`,
  "NL": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "BE": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "CH": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "AT": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "PT": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "IE": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "SE": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "NO": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "DK": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "FI": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "IS": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "PL": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "CZ": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "SK": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "HU": `{name}\n{company}\n{city}\n{street} {houseNumber}\n{street2}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "RO": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "BG": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "HR": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "SI": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "RU": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{city}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "UA": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "BY": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "JP": `{name}\n{company}\n{postalCode}\n{state}{city}\n{street} {houseNumber}\n{street2}\n{country}\nTax Number: {taxNumber}`,
  "KR": `{name}\n{company}\n{postalCode}\n{state} {city}\n{street} {houseNumber}\n{street2}\n{country}\nTax Number: {taxNumber}`,
  "CN": `{name}\n{company}\n{state} {city}\n{street} {houseNumber}\n{street2}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "TW": `{name}\n{company}\n{postalCode}\n{state}{city}\n{street} {houseNumber}\n{street2}\n{country}\nTax Number: {taxNumber}`,
  "HK": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{country}\nTax Number: {taxNumber}`,
  "SG": `{name}\n{company}\n{houseNumber} {street}\n{street2}\nSingapore {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "MY": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{postalCode} {city}, {state}\n{country}\nTax Number: {taxNumber}`,
  "TH": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "VN": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "ID": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "PH": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "IN": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} - {postalCode}\n{state}\n{country}\nTax Number: {taxNumber}`,
  "PK": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "BD": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} - {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "LK": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "AU": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {state} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "NZ": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "TR": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "SA": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "AE": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{country}\nTax Number: {taxNumber}`,
  "ZA": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "EG": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{country}\nTax Number: {taxNumber}`,
  "NG": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city}\n{country}\nTax Number: {taxNumber}`,
  "KE": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "BR": `{name}\n{company}\n{street}, {houseNumber}\n{street2}\n{city} - {state}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "AR": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}, {state}\n{country}\nTax Number: {taxNumber}`,
  "CL": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`,
  "CO": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{city}, {state}\n{postalCode}\n{country}\nTax Number: {taxNumber}`,
  "PE": `{name}\n{company}\n{street} {houseNumber}\n{street2}\n{city} {postalCode}\n{country}\nTax Number: {taxNumber}`,
  "default": `{name}\n{company}\n{houseNumber} {street}\n{street2}\n{postalCode} {city}\n{country}\nTax Number: {taxNumber}`
};
